Repository stevenMarmion/sae_systeme_reseau, pull requests merged in 2024-01, with the labels that each got.

#25 ajout du MCD
  DIAGRAMME_CLASSE_V1/Mocodo/MCD.mcd
  DIAGRAMME_CLASSE_V1/Mocodo/MCD.png
Labels: Analyse, Database

#26 modification du mcd
  DIAGRAMME_CLASSE_V1/Mocodo/MCD.mcd
  DIAGRAMME_CLASSE_V1/Mocodo/MCD.png
Labels: Analyse, Database

#31 Dev classe client bdd
  src/src_class/Message.java
  src/src_class/Server.java
  src/src_class/src_class_commande/CommandeDeleteClient.java
  src/src_class/src_class_commande/CommandeFollow.java
  src/src_class/src_class_commande/CommandeLike.java
  src/src_class/src_class_commande/CommandeUnfollow.java
  src/src_class/src_class_modele/Client.java
  src/src_class/src_class_modele/Message.java
  src/src_class/src_class_modeleBDD/ClientBDD.java
  src/src_class/src_class_modeleBDD/MessageBDD.java
  src/src_exception/ExceptionFollowUser.java
  src/src_exception/ExceptionUnfollowUser.java
  src/src_test/MainClient.java
  src/src_test/MainServer.java
  src/src_test/MainTestClient.java
  src/src_test/MainTestServeur.java
Labels: enhancement, java, Analyse, Database

#33 Résolution de l'erreur de la connexion BDD, erreur résolut. Ajout du …
  .vscode/settings.json
  bin/src_class/Server.class
  bin/src_class/Session.class
  bin/src_class/src_class_commande/Commande.class
  bin/src_class/src_class_commande/CommandeDeleteClient.class
  bin/src_class/src_class_commande/CommandeDeleteServer.class
  bin/src_class/src_class_commande/CommandeFollow.class
  bin/src_class/src_class_commande/CommandeLike.class
  bin/src_class/src_class_commande/CommandeRemove.class
  bin/src_class/src_class_commande/CommandeUnfollow.class
  bin/src_class/src_class_modele/Client.class
  bin/src_class/src_class_modele/Message.class
  bin/src_class/src_class_modeleBDD/ClientBDD.class
  bin/src_class/src_class_modeleBDD/ConnectionBDD.class
  bin/src_class/src_class_modeleBDD/MessageBDD.class
  bin/src_client_serveur/ClientServeur.class
  bin/src_client_serveur/ServerClient.class
  bin/src_exception/ExceptionCommandesAlreadyAdd.class
  bin/src_exception/ExceptionFollowUser.class
  bin/src_exception/ExceptionIpAlreadyDefined.class
  bin/src_exception/ExceptionIpEmpty.class
  bin/src_exception/ExceptionUnfollowUser.class
  bin/src_exception/ExceptionUnfoundMessage.class
  bin/src_test/MainClient.class
  bin/src_test/MainConnectionBDD.class
  bin/src_test/MainServer.class
  bin/src_test/MainTestClient.class
  bin/src_test/MainTestServeur.class
  src/src_class/Server.java
  src/src_class/src_class_modeleBDD/ConnectionBDD.java
  src/src_test/MainConnectionBDD.java
Labels: java, Database, Server

#35 ajout des script de creation et de destruction sql pour la BDD
  DB/script_creation_BDD_table.sql
  DB/script_destruction_BDD_table.sql
Labels: Analyse, Database

#37 ajout de toutes les commandes fonctionnelles pour le Client
  bin/src_class/Server.class
  bin/src_class/Session.class
  bin/src_class/src_class_commande/CommandeDeleteClient.class
  bin/src_class/src_class_commande/CommandeDeleteServer.class
  bin/src_class/src_class_commande/CommandeFollow.class
  bin/src_class/src_class_commande/CommandeLike.class
  bin/src_class/src_class_commande/CommandeRemove.class
  bin/src_class/src_class_commande/CommandeUnfollow.class
  bin/src_class/src_class_modele/Client.class
  bin/src_class/src_class_modeleBDD/ClientBDD.class
  bin/src_class/src_class_modeleBDD/MessageBDD.class
  bin/src_test/MainServer.class
  src/src_class/Server.java
  src/src_class/Session.java
  src/src_class/src_class_commande/CommandeDeleteClient.java
  src/src_class/src_class_commande/CommandeDeleteServer.java
  src/src_class/src_class_commande/CommandeFollow.java
  src/src_class/src_class_commande/CommandeLike.java
  src/src_class/src_class_commande/CommandeRemove.java
  src/src_class/src_class_commande/CommandeUnfollow.java
  src/src_class/src_class_modele/Client.java
  src/src_class/src_class_modeleBDD/ClientBDD.java
  src/src_class/src_class_modeleBDD/MessageBDD.java
  src/src_test/MainServer.java
Labels: enhancement, java, Analyse, Database, Server

#41 ajout de la documentation des classes Commandes et ajout d'une meille…
  bin/src_class/Server.class
  bin/src_class/src_class_commande/CommandeDeleteClient.class
  bin/src_class/src_class_commande/CommandeDeleteServer.class
  bin/src_class/src_class_commande/CommandeFollow.class
  bin/src_class/src_class_commande/CommandeLike.class
  bin/src_class/src_class_commande/CommandeRemove.class
  bin/src_class/src_class_commande/CommandeUnfollow.class
  bin/src_test/MainTestClient.class
  src/src_class/Server.java
  src/src_class/src_class_commande/Commande.java
  src/src_class/src_class_commande/CommandeDeleteClient.java
  src/src_class/src_class_commande/CommandeDeleteServer.java
  src/src_class/src_class_commande/CommandeFollow.java
  src/src_class/src_class_commande/CommandeLike.java
  src/src_class/src_class_commande/CommandeRemove.java
  src/src_class/src_class_commande/CommandeUnfollow.java
  src/src_test/MainServer.java
  src/src_test/MainTestClient.java
Labels: documentation

#42 finition des deux méthodes utiles de la classe AbonnementsBDD.java
  src/src_class/src_class_modeleBDD/AbonnementsBDD.java
  src/src_class/src_class_modeleBDD/ClientBDD.java
Labels: enhancement, java, Database

#46 la classe Session herite maintenant de la classe Thread
  .vscode/settings.json
  RenduIntermediaire_GaelSimon_StevenMarmion.zip
  readme.pdf
  screen_diagramme_classes.png
  src/src_class/Server.java
  src/src_class/Session.java
  src/src_test/MainConnectionBDDGael.java
  src/src_test/MainConnectionBDDSteven.java
  src/src_test/MainTestClient1.java
  src/src_test/MainTestClient2.java
Labels: enhancement, java, Analyse, Thread

#54 Ajout de la nouvelle page de creation d'un message
  src/src_interface/NouveauPoste.java
Labels: enhancement, Analyse, Database, Frontend, JavaFX

#52 Ajout de la page de profil et de son css
  src/src_interface/src_interface_style/darkTheme.css
Labels: enhancement, Frontend, JavaFX

#50 ajout de la page javaFX de recherche
  src/src_interface/Recherche.java
Labels: enhancement, Frontend, JavaFX

#48 ajout de la page d'accueil de notre application
  src/src_interface/Accueil.java
Labels: enhancement, Frontend, JavaFX

#47 Dev interface connexion inscription
  .vscode/launch.json
  .vscode/settings.json
  bin/src_interface/App.class
  src/src_interface/ConnexionInscription.java
Labels: enhancement, Frontend, JavaFX

#62 Dev profil user
  .vscode/launch.json
  DB/script_creation_BDD_table.sql
  DB/script_insert.sql
  bin/src_class/Server.class
  bin/src_class/Session.class
  bin/src_class/src_class_commande/CommandeFollow.class
  bin/src_class/src_class_commande/CommandeUnfollow.class
  bin/src_class/src_class_modele/Client.class
  bin/src_class/src_class_modeleBDD/ClientBDD.class
  bin/src_class/src_class_modeleBDD/MessageBDD.class
  bin/src_test/SessionTest.class
  src/src_class/Server.java
  src/src_class/Session.java
  src/src_class/src_class_commande/CommandeFollow.java
  src/src_class/src_class_commande/CommandeUnfollow.java
  src/src_class/src_class_modele/Client.java
  src/src_class/src_class_modeleBDD/ClientBDD.java
  src/src_class/src_class_modeleBDD/MessageBDD.java
  src/src_test/SessionTest.java
Labels: enhancement, java, Thread
